Lab_PPW_2017/Lab_PPW_2017/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^lab-1/', include(lab_1, namespace='lab-1')),
]

lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list_json, friend_list

urlpatterns = [
     url(r'^$', index, name='index'),
     url(r'^add-friend/$', add_friend, name='add-friend'),
     url(r'^validate-npm/$', validate_npm, name='validate-npm'),
     url(r'^delete-friend/$', delete_friend, name='delete-friend'),
     url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
     url(r'^get-friend-list-json/$', friend_list_json, name='get-friend-list-json'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
from lab_1.views import index as index_lab1
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
	url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
	url(r'^lab-3/', include(lab_3,namespace='lab-3')),
	url(r'^lab-4/', include(lab_4,namespace='lab-4')),
	url(r'^lab-5/', include(lab_5,namespace='lab-5')),
	url(r'^lab-6/', include(lab_6,namespace='lab-6')),
	url(r'^lab-7/', include(lab_7,namespace='lab-7')),
    url(r'^lab-8/', include(lab_7,namespace='lab-8')),
    url(r'^$', RedirectView.as_view(url="/lab-4/", permanent="true"), name='index')
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    added_at = models.DateField(auto_now_add=True)

class Mahasiswa(models.Model):
	nama = models.CharField(max_length=400)
	npm = models.CharField(max_length=250)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    # Page halaman menampilkan list mahasiswa yang ada
    # TODO berikan akses token dari backend dengan menggunakaan helper yang ada

    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()



    friend_list = Friend.objects.all()
    paginator = Paginator(friend_list, 30)
    page = request.GET.get('page')
    response = {"mahasiswa_list": mahasiswa_list, "friend_list": friend_list, "author" : "Davin"}
    html = 'lab_7/lab_7.html'
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        friend = Friend(friend_name=name, npm=npm)
        friend.save()
        data = model_to_dict(friend)
        return HttpResponse(data)

def delete_friend(request, friend_id):
    Friend.objects.filter(id=friend_id).delete()
    return HttpResponseRedirect('/lab-7/')

def friend_list_json(request):
    friend = Friend.objects.all()
    data = serializers.serialize("json", friend)
    return HttpResponse(data, content_type='application/json')

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    num_result = Friend.objects.filter(npm = npm).count()
    data = {
        'is_taken': (num_result > 0)  #lakukan pengecekan apakah Friend dgn npm tsb sudah ada
    }
    return JsonResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data
from django.shortcuts import render

# Create your views here.

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
       #map {
           width: 100%;
           height: 400px;
           background-color: grey;
         }
      /* Optional: Makes the sample page fill the window. */
      .controls {
        margin-top: 10px;
        border: 1px solid transparent;
        border-radius: 2px 0 0 2px;
        box-sizing: border-box;
        -moz-box-sizing: border-box;
        height: 32px;
        outline: none;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
      }

      #pac-input {
        background-color: #fff;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        padding: 0 11px 0 13px;
        text-overflow: ellipsis;
        width: 300px;
      }

      #pac-input:focus {
        border-color: #4d90fe;
      }

      .pac-container {
        font-family: Roboto;
      }

      #type-selector {
        color: #fff;
        background-color: #4d90fe;
        padding: 5px 11px 0px 11px;
      }

      #type-selector label {
        font-family: Roboto;
        font-size: 13px;
        font-weight: 300;
      }
      #target {
        width: 345px;
      }
    </style>
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h2> Friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">
                        {% if friend_list %}
                            {% csrf_token %}
                            <div id="all-friend"></div>
                        {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                        {% endif %}
                    </div>
                    <a href="/lab-7/">
                        <button style="margin-left: 200px;">Kembali ke Halaman Utama</button>
                    </a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $( document ).ready(function () {
            {# lengkapi pemanggilan ajax berikut untuk mengambil daftar teman yang ada di database #}
            $.ajax({
                method: "GET",
                url: '{% url "lab-7:get-friend-list-json" %}',
                dataType: 'json',
                success: function (data) {
                    console.log(data.length);
                    if (data.length == 0) {
                        html = '<div class="alert alert-danger text-center">' +
                                '<strong>Opps!</strong> Tidak ada teman' +
                            +'</div>';
                        $("#all-friend").append(html);
                    }
                    else {
                        console.log(data)
                        for (var key in data){
                        console.log(key);
                        var buttonDelete = '<span class="btn btn-default btn-danger" onClick="deleteFriend('+ "'" + data[key].fields.friend_name + "'" 
                            + ', '+ "'" + data[key].fields.npm + "'" + ');"'+ 'style="float: right; margin-left: 5px;"'+'>Delete</span>';
                        var addressButton = '<span class="btn btn-default btn-danger" id="searchButton" onClick="checkAddress('+ "'" + data[key].fields.alamat + "'" 
                            +'); refreshGmap(' + "'" + data[key].fields.npm + "'" + ');"'+ 'style="float: right; background-color: blue;"'+'>Data</span>';
                        var dataMahasiswa = '<div class="list-group-item clearfix" id="data-' + data[key].fields.npm + '" style="display: none;">' + '<a class="list-group-item clearfix">Nama Lengkap: ' +
                            data[key].fields.friend_name + '</a>' + '<a class="list-group-item clearfix">NPM: ' +
                            data[key].fields.npm + '</a>' + '<a class="list-group-item clearfix">' + '</a>' + '</div>';
                        html = '<a class="list-group-item clearfix" '+ 'id='+ data[key].fields.npm + '>' +
                            data[key].fields.friend_name + " (" + data[key].fields.npm + ")"+ buttonDelete + addressButton + dataMahasiswa +
                            '</a>';
                        $("#all-friend").append(html);
                        }
                    }
                    
                },
                error: function(error){
                    alert("Data gagal diterima");
                    html = '<div class="alert alert-danger text-center">' +
                                '<strong>Opps!</strong> Tidak ada teman' +
                            +'</div>';
                    $("#all-friend").append(html);
                }
            });
        });

        var deleteFriend = function(nama, npm) {
            $.ajax({
                method: "POST",
                url: '{% url "lab-7:delete-friend" %}',
                data: { name: nama, npm: npm},
                success : function (response) {
                    $("#" + npm).remove()
                },
                error : function (error) {
                    alert("Mahasiswa tersebut tidak ada");
                }
            });
         };

    </script>
    <script>
        var checkAddress = function(alamat) {
            $('#pac-input').val(alamat);
         };

        var refreshGmap = function (npm) {
            var box = document.getElementById('data-' + npm);
              if (box.style.display === "block"){
                box.style.display = "none";
              }
              else {
                var input = document.getElementById('pac-input');
                google.maps.event.trigger(input, 'focus')
                google.maps.event.trigger(input, 'keydown', { keyCode: 13 });
                box.style.display = "block";
              }
        };    
      function initAutocomplete() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -2.407468, lng: 112.363101},
          zoom: 5,
          mapTypeId: 'roadmap'
        });

        var marker = new google.maps.Marker({
          position: {lat: -2.407468, lng: 112.363101},
          map: map,
        });

        // Create the search box and link it to the UI element.
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });

        var markers = [];
        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

          if (places.length == 0) {
            return;
          }

          // Clear out the old markers.
          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];

          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {
            if (!place.geometry) {
              console.log("Returned place contains no geometry");
              return;
            }
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(25, 25)
            };

            // Create a marker for each place.
            markers.push(new google.maps.Marker({
              map: map,
              icon: icon,
              title: place.name,
              position: place.geometry.location
            }));

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyALpWCOORH_gKX_X55Svi7JUyK2q0JVxNA&libraries=places&callback=initAutocomplete"
         async defer></script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}

{% block javascript %}
<script>
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:add-friend" %}',
            data: { name: nama, npm: npm},
            dataType: 'json',
            success : function (friend) {
                html = '<a class="list-group-item clearfix">' +
                    friend.friend_name + " (" + friend.npm + ")" +
                    '</a>';
                $("#friend-list").append(html);
            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    $("#add-friend").on("submit", function () {
        name = $("#field_name").val()
        npm = $("#field_npm").val()
        addFriend(name, npm)
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm,
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}

<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                        <div class="list-group-item clearfix" style="text-align: center;">
                            <div class="pagination">
                                <span class="step-links">
                                    {% if mahasiswa_list.has_previous %}
                                        <a href="?page={{ mahasiswa_list.previous_page_number }}" style="margin-right: 100px;">Previous</a>
                                    {% endif %}

                                    <span class="current">
                                        Page {{ mahasiswa_list.number }} of {{ mahasiswa_list.paginator.num_pages }}.
                                    </span>

                                    {% if mahasiswa_list.has_next %}
                                        <a href="?page={{ mahasiswa_list.next_page_number }}" style="margin-left: 100px;">Next</a>
                                    {% endif %}
                                </span>
                            </div>
                        </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}